FROM phpdockerio/php72-fpm:latest

WORKDIR "/veus-backend"

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -q -y install --no-install-recommends ca-certificates curl acl sudo \
    php7.2-mbstring php-xdebug \
    php7.2-xml php7.2-json php7.2-mysql php7.2-pdo-mysql php7.2-sockets \
    php7.2-gd php7.2-curl php7.2-soap

RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*